---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/.vim/latex-template/svm-latex-ms.tex
bibliography: master.bib
header-includes:
  -  \usepackage{hyperref}
biblio-style: apsr
title: "A Pandoc Markdown Article Starter and Template"
thanks: "Replication files are available on the author's Github account (http://github.com/svmiller). **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: svmille@clemson.edu."
author:
- name: Steven V. Miller
  affiliation: Clemson University
abstract: "This document provides an introduction to R Markdown, argues for its benefits, and presents a sample manuscript template intended for an academic audience. I include basic syntax to R Markdown and a minimal working example of how the analysis itself can be conducted within R with the `knitr` package."
keywords: "pandoc, r markdown, knitr"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
endnote: no
---

# Introduction

Academic workflow, certainly in political science, is at a crossroads. The *American
Journal of Political Science* (*AJPS*) announced a (my words) ["show your work"
initiative](http://ajps.org/2015/03/26/the-ajps-replication-policy-innovations-and-revisions/)
in which authors who are tentatively accepted for publication at the journal must hand
over the raw code and data that produced the results shown in the manuscript. The
editorial team at *AJPS* then reproduces the code from the manuscript. Pending
successful replication, the manuscript moves toward publication. The *AJPS* might be at
the fore of this movement, and it could be the most aggressive among political science
journals, but other journals in our field have signed the joint [Data Access & Research
Transparency](http://www.dartstatement.org/) (DART) initiative. This, at a bare minimum,
requires uploading code from quantitatively-oriented published articles to in-house
directories hosted by the journal or to services like
[Dataverse](http://dataverse.org/). 

Perhaps the greatest intrigue of R Markdown comes with the [`knitr`
package](http://yihui.name/knitr/) provided by @xie2013ddrk. In other words, the author
can, if she chooses, do the analysis in the Markdown document itself and compile/execute
it in R.

<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->
